### PR TITLE
Port NAGI to MacOS and other fixes

### PR DESCRIPTION
**Pull request by Ritchie333**
I've had a copy of NAGI sitting around for many years and over Christmas I got a chance to make some (possible) improvements to it. Main differences are:

* SDL upgraded to version 2.0 - allows full-screen on all platforms and resizing of windows
* Menus now respond to mouse clicks
* Closing the application window invokes the "quit" command - allows for a graceful exit
* Build procedure changed to use GNU autoconf, tested on MacOS with MacPorts, Debian Linux and Windows with MSYS Mingw64 (though the latter was a pain in the neck). Would also like to try a port to Android and ARM Linux (eg: Raspberry Pi) at some point.
* Fixed bug where attempting to load ancient saved games from the original DOS AGI interpreter would just crash (this is because the view structure uses 16-bit pointers, NAGI uses whatever it's given by the C compiler).

If that all sounds good, let me know so we can migrate this to the base.

### CODE REVIEW

**Comment by sonneveld** [comment]
This is great! Please allow me a bit of time to review.

**Comment by sonneveld** [comment]
A couple of notes:

- I love the menu mouse support!
- SDL2 port seems to work well on OSX. I've noticed that the key mapping is a bit off in places, with ctrl and shifted upper row keys.  I suspect some of that could be fixed by using sdl2's TEXT_INPUT events.
- A while ago I started work on using cmake instead of autoconf.  I think it's a bit simpler and supports xcode and visual studio. I probably wouldn't have both autoconf and cmake build scripts though.
- Nice work on fixing older saves!  I'm not sure how well it would work across different AGI interpreter versions but it's nice to have!

Considering 'master' is still in a pre-release state, would you mind if I accepted your pull request with the understanding that I would probably replace the autoconf scripts with cmake?  The other issues I've found can be fixed later as well.  Or do you think these changes should be broken up into individual pull requests?  I'm not too bothered with having a pristine git history.

**Comment by Ritchie333** [comment]
Hi Nick,

I think the best thing to do is accept it and change it over to cmake. I only managed to make the changes because I had time off from my day job over Christmas to tinker with the code, and had been meaning to for some time. I don't have any particular attachment to autoconf aside from everyone else uses. I struggled to get the application icon generation working properly. If you're used to cmake, go with that.

I'll have a look at the keymapping issue if I get time; it may be just a simple bug.

The older saves issue is not really fixed per se - I mean, it won't crash now, just bring up an error message, but the problem is that legacy saved games from actual Sierra games are 16 bit binaries. In modern C compilers, not only are pointers 64 bit, but structure alignment and packing means that the binary structure can be wildly different. See http://www.catb.org/esr/structure-packing/. If I had lots of time I would probably replace the whole area with an actual file open dialog (using wxWidgets perhaps?) and possibly switch the save game format over to a text-based format, with a "legacy" option for people who really want to save and load games just as they did 30 years ago, and possibly a separate app to migrate old saved games.

**Comment by StephenCleary** [comment]
> Would also like to try a port to Android and ARM Linux (eg: Raspberry Pi) at some point.

+100 for Pi support. :D

**Comment by sonneveld** [comment]
Sorry about this, my first pull request for my project and I forgot about it for a year. I merged as is like you suggested and I'll see about fixing the issues I found. Thanks and sorry again! :)

**Pull request merged**
